<?php

declare(strict_types=1);

// Stable compatibility bootstrap. New Attendance application/domain services
// are appended here as they are introduced; Composer supplies the documented
// Staff contracts without changing any legacy HTTP entrypoint.
require_once dirname(__DIR__, 3) . '/vendor/autoload.php';

$attendanceModuleFiles = [
    'Contracts/AttendanceTransactionManager.php',
    'Contracts/BiometricIdentityResolver.php',
    'Contracts/BiometricIdentityMappingRepository.php',
    'Contracts/AttendanceEventRepository.php',
    'Contracts/AttendanceEntryMethodQuery.php',
    'Contracts/AlternativeAttendanceAuthorization.php',
    'Contracts/AlternativeAttendanceEventRepository.php',
    'Contracts/AttendanceAdjustmentAuthorization.php',
    'Contracts/AttendanceAdjustmentRepository.php',
    'Contracts/AttendanceExceptionQuery.php',
    'Contracts/AttendanceEventWindowQuery.php',
    'Contracts/AttendanceShadowRunRepository.php',
    'Contracts/AttendanceRecalculationRepository.php',
    'Contracts/AttendancePeriodRepository.php',
    'Contracts/AttendanceReportReadRepository.php',
    'Contracts/AttendanceReportProjectionRepository.php',
    'Contracts/ApprovedCoverageQuery.php',
    'Contracts/EffectiveScheduleQuery.php',
    'Contracts/LeaveWorkdayCalendarQuery.php',
    'Contracts/LegacyStaffAttendanceDayQuery.php',
    'Contracts/LegacyStaffShiftAuditWriter.php',
    'Contracts/LegacyStaffShiftRepository.php',
    'Contracts/SchedulePolicyReadRepository.php',
    'Contracts/SchedulePolicyRepository.php',
    'Contracts/ScheduleChangeAuthorization.php',
    'Domain/Schedule/WorkSchedule.php',
    'Domain/Calculation/PunchWindowMatcher.php',
    'Domain/Calculation/AttendanceDayCalculator.php',
    'Application/EffectiveScheduleQueryService.php',
    'Application/LeaveWorkdayCalendarQueryService.php',
    'Application/BiometricIdentityMappingService.php',
    'Application/AttendanceEventIngestor.php',
    'Application/BiometricCsvImportPreparationService.php',
    'Application/AlternativeAttendanceRecorder.php',
    'Application/AttendanceAdjustmentService.php',
    'Application/AttendanceExceptionQueryService.php',
    'Application/AttendanceShadowRunService.php',
    'Application/AttendanceRecalculationService.php',
    'Application/AttendancePeriodService.php',
    'Application/AttendanceReportScope.php',
    'Application/AttendanceReportQueryService.php',
    'Application/AttendanceReportProjector.php',
    'Application/SchedulePolicyAdminQueryService.php',
    'Application/SchedulePolicyCommandService.php',
    'Application/ScheduleChangeRequestService.php',
    'Application/SchedulePolicyImpactQuery.php',
    'Application/LegacyStaffShiftCompatibilityService.php',
    'Infrastructure/PdoAttendanceTransactionManager.php',
    'Infrastructure/PdoBiometricIdentityMappingRepository.php',
    'Infrastructure/PdoAttendanceEventRepository.php',
    'Infrastructure/PdoAlternativeAttendanceEventRepository.php',
    'Infrastructure/StaffAlternativeAttendanceAuthorization.php',
    'Infrastructure/PdoAttendanceAdjustmentRepository.php',
    'Infrastructure/PdoAttendanceExceptionQuery.php',
    'Infrastructure/StaffAttendanceAdjustmentAuthorization.php',
    'Infrastructure/PdoAttendanceShadowRunRepository.php',
    'Infrastructure/PdoAttendancePeriodRepository.php',
    'Infrastructure/PdoAttendanceReportReadRepository.php',
    'Infrastructure/PdoAttendanceReportProjectionRepository.php',
    'Infrastructure/StaffApprovedCoverageChangeGateway.php',
    'Infrastructure/PdoApprovedCoverageQuery.php',
    'Infrastructure/PdoLegacyStaffAttendanceDayQuery.php',
    'Infrastructure/PdoSchedulePolicyRepository.php',
    'Infrastructure/ScheduleChangeApprovalOutcomeHandler.php',
    'Infrastructure/PdoScheduleChangeAuthorization.php',
    'Infrastructure/PdoLegacyStaffShiftRepository.php',
    'Infrastructure/OperationsAuditLegacyStaffShiftWriter.php',
    'Infrastructure/AttendanceModuleFactory.php',
    'Presentation/BiometricImportErrorPresenter.php',
    'Presentation/AttendanceReportExporter.php',
    'SpecialistAttendanceReadService.php',
];

foreach ($attendanceModuleFiles as $attendanceModuleFile) {
    require_once __DIR__ . '/' . $attendanceModuleFile;
}
