<?php

declare(strict_types=1);

return [
    'src/Modules/Students/StudentOperationLogQuery.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Students/StudentOperationLogQuery.php',
        'reason' => 'Read-only Student Affairs audit query; undo and redo terms describe eligibility filters and lookup methods but this class never changes business or audit data.',
        'evidence' => 'Every SQL statement is SELECT or COUNT; student_operations.php delegates the separately authorized mutation to the shared UndoManager only after this query validates the exact year-scoped activity/undo pair.',
    ],
    'admin/assessment_teacher_assignments.php' => [
        'type' => 'delegated',
        'owner' => 'admin/assessment_teacher_assignments.php and classes/ActivityLog.php',
        'reason' => 'The page owns one transaction for replacing a teacher\'s assignment set and fails closed when the shared ActivityLog::logChange audit write fails.',
        'evidence' => 'The save handler starts a PDO transaction, persists requested/effective activation state, calls ActivityLog::logChange, then commits; its catch block rolls back.',
    ],
    'classes/AssessmentTeacherAssignmentActivationService.php' => [
        'type' => 'delegated',
        'owner' => 'AssessmentSubjectAssignmentGroupService.php and admin/assessment_subject_assignments.php',
        'reason' => 'The activation reconciler is invoked inside its callers\' subject-link transaction and rejects the caller when its mandatory ActivityLog::logChange audit write fails.',
        'evidence' => 'synchronize locks assignment rows, updates effective activation and pending reason, writes ActivityLog::logChange, and throws on audit failure before the caller commits.',
    ],
    'classes/AssessmentSchemeScopeResolver.php' => [
        'type' => 'false_positive',
        'owner' => 'classes/AssessmentSchemeScopeResolver.php',
        'reason' => 'Read-only assessment-scope resolver; its FOR UPDATE clauses serialize caller-owned transactions without mutating assessment data.',
        'evidence' => 'All SQL statements in the resolver are SELECT queries; it only resolves, validates, counts, or locks scope rows, while audited command services own the subsequent writes.',
    ],
    'admin/assessment_scheme_batch.php' => [
        'type' => 'delegated',
        'owner' => 'classes/AssessmentSchemeBatchService.php',
        'reason' => 'The page validates the request and delegates batch creation to the transaction-owning assessment command service.',
        'evidence' => 'AssessmentSchemeBatchService::create records every created family, scheme, scope, annual policy, and policy-term through AuditService before committing the batch.',
    ],
    'admin/assessment_scheme_family.php' => [
        'type' => 'delegated',
        'owner' => 'classes/AssessmentSchemeBatchService.php',
        'reason' => 'The family-management page validates the request and delegates draft configuration plus lifecycle transitions to the transaction-owning assessment command service.',
        'evidence' => 'AssessmentSchemeBatchService::updateFamilyConfiguration, ::activateFamily, and ::archiveFamily use the shared AuditService and one batch identifier before committing.',
    ],
    'src/Modules/Staff/Infrastructure/Organization/PdoStaffOrganizationRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Organization/StaffOrganizationService.php',
        'reason' => 'The PDO adapter persists only validated Staff organization commands inside the application service transaction.',
        'evidence' => 'Each StaffOrganizationService creation path calls repository->transactional, persists through this adapter, and records a mandatory AuditEventWriter event before returning to the transaction boundary.',
    ],
    'src/Modules/Staff/Infrastructure/Timeline/PdoStaffCredentialRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Timeline/StaffDocumentExpiryService.php',
        'reason' => 'The PDO adapter persists immutable credential evidence only inside the application service transaction.',
        'evidence' => 'StaffDocumentExpiryService::registerCredential opens the repository transaction, inserts through this adapter, then requires AuditEventWriter::recordEvent before the transaction can commit.',
    ],
    'admin/ajax_staff_attendance_audit_datatable.php' => [
        'type' => 'false_positive',
        'owner' => 'admin/ajax_staff_attendance_audit_datatable.php',
        'reason' => 'Read-only server-side DataTable endpoint; update/delete words describe attendance audit rows and no state is changed.',
        'evidence' => 'The endpoint executes only paginated SELECT/count queries and emits JSON.',
    ],
    'admin/class_lists.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Students/StudentProfileCommandService.php and src/Modules/Students/StudentChangeRequestService.php',
        'reason' => 'The entrypoint validates the class-list request and delegates admin transfers and specialist proposals to transaction-owning audited student services.',
        'evidence' => 'Admin batches call StudentProfileCommandService::applyClassTransfer with one shared batch identifier; specialist batches call StudentChangeRequestService::submitClassTransfer.',
    ],
    'admin/new_students.php' => [
        'type' => 'false_positive',
        'owner' => 'admin/new_students.php',
        'reason' => 'Read-only derived-student list; lexical update markers occur in client-side filter labels.',
        'evidence' => 'No server-side INSERT, UPDATE, DELETE, or mutating service call.',
    ],
    'admin/transferred_students.php' => [
        'type' => 'delegated',
        'owner' => 'admin/students.php and audited student command services',
        'reason' => 'Read requests render the transferred list; POST requests delegate to the protected student entrypoint and its transaction-owning services.',
        'evidence' => "POST defines STUDENT_DATA_SCOPE='transferred' and requires admin/students.php.",
    ],
    'classes/AcademicYearWriteGuard.php' => [
        'type' => 'false_positive',
        'owner' => 'classes/AcademicYearWriteGuard.php',
        'reason' => 'Read-only fail-closed policy guard; FOR UPDATE serializes a caller-owned transaction and performs no mutation.',
        'evidence' => 'AcademicYearWriteGuard::assertWritable executes SELECT only and throws when the year is missing, inactive, or locked.',
    ],
    'classes/SystemAdministratorRoleService.php' => [
        'type' => 'false_positive',
        'owner' => 'classes/SystemAdministratorRoleService.php',
        'reason' => 'Read-only fail-closed authorization policy; FOR UPDATE locks administrator rows inside the caller-owned audited transaction and performs no mutation.',
        'evidence' => 'All service SQL statements are SELECT queries; admin/staff_accounts.php owns the role/status UPDATE and mandatory ActivityLog write in one transaction.',
    ],
    'classes/NewYearWizard.php' => [
        'type' => 'delegated',
        'owner' => 'classes/NewYearRolloverService.php',
        'reason' => 'The public compatibility adapter delegates preview and execution to the transaction-owning safe rollover service.',
        'evidence' => 'NewYearWizard::preview and execute construct NewYearRolloverService; legacy private helpers are unreachable from the public workflow.',
    ],
    'src/Modules/Accounts/AccountCredentialCsvService.php' => [
        'type' => 'delegated',
        'owner' => 'AccountCredentialCsvService with the page-supplied unified audit writer',
        'reason' => 'The service owns the atomic credential import and requires its injected audit writer to succeed for every changed account before commit.',
        'evidence' => 'AccountCredentialCsvService::import rolls back when auditWriter does not return true; staff_accounts.php and student_accounts.php inject ActivityLog-backed writers with one batch_id.',
    ],
    'admin/academic_year_setup.php' => [
        'type' => 'delegated',
        'owner' => 'classes/RecoveryBackupService.php and classes/NewYearRolloverService.php',
        'reason' => 'The admin entrypoint validates the protected request and delegates recovery and rollover mutations to transaction-owning services.',
        'evidence' => 'RecoveryBackupService and NewYearRolloverService own persistence, audit, verification, and rollback.',
    ],
    'admin/ajax_assessment_marks_sheet.php' => [
        'type' => 'false_positive',
        'owner' => 'classes/AssessmentMarkSheetQuery.php',
        'reason' => 'CSRF-protected POST is used only to load the spreadsheet read model; the endpoint performs no state change.',
        'evidence' => 'AssessmentMarkSheetQuery::load executes SELECT queries and returns JSON.',
    ],
    'admin/ajax_assessment_mark_update.php' => [
        'type' => 'delegated',
        'owner' => 'classes/AssessmentMarkAdministrationService.php',
        'reason' => 'The endpoint validates admin session, CSRF, and current-year scope, then delegates the mutation to the audited mark command owner.',
        'evidence' => 'AssessmentMarkAdministrationService::updateMark owns locking, transaction, domain audit, shared audit, and rollback.',
    ],
    'admin/ajax_assessment_marks_bulk.php' => [
        'type' => 'delegated',
        'owner' => 'classes/AssessmentMarkAdministrationService.php',
        'reason' => 'The endpoint validates admin session, CSRF, current-year scope and dispatches only to the atomic audited mark command owner.',
        'evidence' => 'AssessmentMarkAdministrationService::bulkUpdateMarks and deleteMarks use one transaction and batch_id for the complete selection.',
    ],
    'tools/create_recovery_backup.php' => [
        'type' => 'delegated',
        'owner' => 'classes/RecoveryBackupService.php',
        'reason' => 'CLI adapter delegates package creation and receipt audit to the recovery service.',
        'evidence' => 'RecoveryBackupService::createPackage',
    ],
    'tools/verify_recovery_backup.php' => [
        'type' => 'delegated',
        'owner' => 'classes/RecoveryBackupService.php',
        'reason' => 'CLI adapter delegates isolated restore verification and receipt audit to the recovery service.',
        'evidence' => 'RecoveryBackupService::verifyPackage',
    ],
    'admin/staff.php' => [
        'type' => 'delegated',
        'owner' => 'StaffProfileCommandService, StaffAttachmentService, StaffDeletionService, profile_excel_import.php',
        'reason' => 'All staff mutations are delegated to transaction-owning services or the atomic import owner.',
        'evidence' => 'create/update/deleteAttachment/delete/profile_import_staff owners contain audit calls.',
    ],
    'admin/students.php' => [
        'type' => 'delegated',
        'owner' => 'StudentBulkCreateService, StudentArchiveService, StudentAttachmentService, StudentProfileCommandService, profile_excel_import.php',
        'reason' => 'All student mutations are delegated to service owners or the atomic import owner.',
        'evidence' => 'create/archive/attachment/save/profile_import_student owners contain audit calls.',
    ],
    'admin/pending_operations.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Students/StudentChangeRequestService.php',
        'reason' => 'The admin review page validates the request and delegates approval/rejection, transactions, conflict detection, and audit persistence to the student change-request owner.',
        'evidence' => 'StudentChangeRequestService::approve and StudentChangeRequestService::reject.',
    ],
    'admin/student_archive.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Students/StudentArchiveService.php',
        'reason' => 'Archive restoration and guarded permanent deletion delegate to the transaction-owning student service.',
        'evidence' => 'StudentArchiveService::restore and StudentArchiveService::permanentlyDelete own audit and rollback.',
    ],
    'admin/ajax_student_completeness.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Students/StudentCompletenessConfigService.php',
        'reason' => 'The endpoint validates authorization and CSRF, then delegates the only mutation to the transaction-owning settings service.',
        'evidence' => 'StudentCompletenessConfigService::save persists settings and the shared audit/undo record in one transaction.',
    ],
    'src/Modules/Students/StudentOperationalGuard.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Students/StudentOperationalGuard.php',
        'reason' => 'Read-only eligibility guard; FOR UPDATE only locks the student identity inside a caller-owned transaction and performs no mutation.',
        'evidence' => 'Both methods execute SELECT statements only; audited application services and entrypoints own the subsequent writes.',
    ],
    'admin/data_versions.php' => [
        'type' => 'delegated',
        'owner' => 'classes/UndoManager.php',
        'reason' => 'The page only invokes the central undo engine; mutation and audit outcome are owned there.',
        'evidence' => 'UndoManager::undo',
    ],
    'api/undo.php' => [
        'type' => 'delegated',
        'owner' => 'classes/UndoManager.php',
        'reason' => 'The endpoint validates the request and delegates the state change and audit outcome to the central undo engine.',
        'evidence' => 'UndoManager::undo',
    ],
    'admin/manage_backups.php' => [
        'type' => 'delegated',
        'owner' => 'classes/EvaluationBackupService.php',
        'reason' => 'Restore and delete are transactionally audited by the backup service owner.',
        'evidence' => 'EvaluationBackupService::restore/delete',
    ],
    'admin/staff_attendance_audit.php' => [
        'type' => 'false_positive',
        'owner' => 'admin/staff_attendance_audit.php',
        'reason' => 'Read-only report; lexical write markers occur in presentation text or scripts.',
        'evidence' => 'No server-side INSERT, UPDATE, DELETE, or mutating service call.',
    ],
    'admin/student_evaluations.php' => [
        'type' => 'false_positive',
        'owner' => 'admin/student_evaluations.php',
        'reason' => 'This entrypoint renders and queries; JavaScript update/delete labels target separate handlers.',
        'evidence' => 'No server-side mutation handler in this file.',
    ],
    'admin/student_statistics.php' => [
        'type' => 'false_positive',
        'owner' => 'admin/student_statistics.php',
        'reason' => 'Read-only statistics page; update markers are JavaScript customization labels.',
        'evidence' => 'No server-side mutation handler in this file.',
    ],
    'teacher/attendance.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Students/StudentAttendanceService.php',
        'reason' => 'The teacher entrypoint validates the scoped class request and delegates the complete attendance mutation to the transaction-owning student attendance service.',
        'evidence' => 'StudentAttendanceService::saveClassDay validates the exact locked roster, upserts without destructive replacement, and records audit/undo entries before commit.',
    ],
    'teacher/lesson_view.php' => [
        'type' => 'false_positive',
        'owner' => 'teacher/lesson_view.php',
        'reason' => 'Read-only lesson view; the update marker is a JavaScript UI comment.',
        'evidence' => 'No server-side mutation handler in this file.',
    ],
    'teacher/index.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/BehaviorEvaluation/Evaluation.php',
        'reason' => 'The only server mutation delegates evaluation creation to the transaction-owning domain model.',
        'evidence' => 'Evaluation::create performs locked duplicate validation, insert, and central audit.',
    ],
    'teacher/evaluations.php' => [
        'type' => 'false_positive',
        'owner' => 'teacher/evaluations.php',
        'reason' => 'The update marker occurs in client-side UI code; this entrypoint has no server mutation.',
        'evidence' => 'No server-side SQL write or mutating service call.',
    ],
    'teacher/ajax/generate_lesson.php' => [
        'type' => 'delegated',
        'owner' => 'classes/LessonGenerator.php and src/Modules/LearningContent/AiLessonLifecycleService.php',
        'reason' => 'Lesson creation/result persistence and lifecycle state transitions are owned by transactionally audited services.',
        'evidence' => 'LessonGenerator::createLesson/saveResults and AiLessonLifecycleService::update.',
    ],
    'teacher/ajax/generate_powerpoint_only.php' => [
        'type' => 'delegated',
        'owner' => 'classes/LessonGenerator.php and src/Modules/LearningContent/AiLessonLifecycleService.php',
        'reason' => 'Lesson creation/result persistence and every PowerPoint lifecycle transition delegate to audited owners.',
        'evidence' => 'LessonGenerator::createLesson/saveResults and AiLessonLifecycleService::update.',
    ],
    'teacher/training.php' => [
        'type' => 'delegated',
        'owner' => 'classes/Training.php',
        'reason' => 'The only mutation is enrollment, which delegates to the transaction-owning training service.',
        'evidence' => 'Training::enrollTeacher records the insert event in the same transaction.',
    ],
    'teacher/training_my.php' => [
        'type' => 'false_positive',
        'owner' => 'teacher/training_my.php',
        'reason' => 'Read-only course and certificate view; export actions only create client-side downloads.',
        'evidence' => 'No server-side SQL write or mutating service call.',
    ],
    'specialist/evaluation_reports.php' => [
        'type' => 'false_positive',
        'owner' => 'specialist/evaluation_reports.php',
        'reason' => 'Read-only report and Excel export; lexical update/delete markers are client-side selection behavior.',
        'evidence' => 'No server-side INSERT, UPDATE, DELETE, or mutating service call.',
    ],
    'src/Modules/Staff/Presentation/list_view.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Staff/Presentation/list_view.php',
        'reason' => 'Presentation template only; write markers are labels and client-side interactions.',
        'evidence' => 'No server-side database handle, SQL execution, or mutating service call.',
    ],
    'src/Modules/Students/Presentation/list_view.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Students/Presentation/list_view.php',
        'reason' => 'Presentation template delegates mutations to the audited AJAX dispatcher.',
        'evidence' => 'Server-side template contains no SQL write; fetch calls target includes/ajax_handlers.php.',
    ],
    'classes/Presentation/ClassLists/page_scripts.php' => [
        'type' => 'false_positive',
        'owner' => 'classes/Presentation/ClassLists/page_scripts.php',
        'reason' => 'Client-side script template only; fetch requests delegate work to class_lists.php.',
        'evidence' => 'No server-side SQL execution or business mutation in this file.',
    ],
    'classes/Presentation/Dashboard/interactions.php' => [
        'type' => 'false_positive',
        'owner' => 'classes/Presentation/Dashboard/interactions.php',
        'reason' => 'Client-side dashboard interactions; update markers refer to DOM state.',
        'evidence' => 'No server-side database write or mutating service call.',
    ],
    'classes/Presentation/LessonPrep/scripts_part_one.php' => [
        'type' => 'false_positive',
        'owner' => 'classes/Presentation/LessonPrep/scripts_part_one.php',
        'reason' => 'Client-side lesson preparation script; mutations are delegated to audited AJAX endpoints.',
        'evidence' => 'No server-side database write in the presentation template.',
    ],
    'classes/Presentation/LessonPrep/scripts_part_two.php' => [
        'type' => 'false_positive',
        'owner' => 'classes/Presentation/LessonPrep/scripts_part_two.php',
        'reason' => 'Client-side lesson preparation script; mutations are delegated to audited AJAX endpoints.',
        'evidence' => 'No server-side database write in the presentation template.',
    ],
    'src/Modules/BehaviorEvaluation/Ajax/evaluations.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/BehaviorEvaluation/Evaluation.php',
        'reason' => 'The dispatcher validates role and scope, then delegates every evaluation mutation to the transaction-owning model.',
        'evidence' => 'Evaluation::create/delete/deleteAndRecalculatePoints/deleteAllForStudent own central audit and rollback.',
    ],
    'classes/ActivityLog.php' => [
        'type' => 'delegated',
        'owner' => 'classes/ActivityLog.php',
        'reason' => 'This file is the central append-only audit sink; recursively auditing its own inserts is neither meaningful nor finite.',
        'evidence' => 'ActivityLog::log stores correlation, actor, result, route, and redacted details for AuditService.',
    ],
    'classes/Ajax/Handlers/reports.php' => [
        'type' => 'false_positive',
        'owner' => 'classes/Ajax/Handlers/reports.php',
        'reason' => 'Read-only report handlers; lexical write markers occur in labels or non-mutating query text.',
        'evidence' => 'All database statements are SELECT/count/report queries.',
    ],
    'classes/ExamTemplateRenderer.php' => [
        'type' => 'false_positive',
        'owner' => 'classes/ExamTemplateRenderer.php',
        'reason' => 'HTML and JavaScript renderer only; update markers refer to browser progress and UI state.',
        'evidence' => 'No database dependency or server-side SQL execution.',
    ],
    'classes/utilities.php' => [
        'type' => 'delegated',
        'owner' => 'classes/ActivityLog.php',
        'reason' => 'The legacy logAction API now delegates to the unified audit sink instead of writing a parallel action log.',
        'evidence' => 'Utilities::logAction calls ActivityLog::log with an explicit actor identifier.',
    ],
    'classes/Ajax/Handlers/lookups.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Students/StudentRelationshipService.php',
        'reason' => 'The only mutation is kinship linking, now restricted to CSRF-protected POST and delegated to the transaction-owning relationship service.',
        'evidence' => 'link_kinship constructs StudentRelationshipService and invokes link; no direct SQL writes remain.',
    ],
    'classes/ProfileAttachmentStorage.php' => [
        'type' => 'delegated',
        'owner' => 'StudentAttachmentService, StaffAttachmentService, audited attachment migration tools',
        'reason' => 'This low-level storage adapter has no database mutation or business identity; transaction-owning callers audit attachment metadata before cleanup.',
        'evidence' => 'store/delete/copy only manipulate private files; attachment services and migration commands own database state and audit correlation.',
    ],
    'classes/OllamaAI.php' => [
        'type' => 'delegated',
        'owner' => 'AI request lifecycle owners and ai_api_logs telemetry sink',
        'reason' => 'The sole database write appends operational usage telemetry; business lesson, media, and chat outcomes are audited by their request owners.',
        'evidence' => 'OllamaAI::logUsage only inserts timing/token/status telemetry and does not mutate a business entity.',
    ],
    'classes/excel_handler.php' => [
        'type' => 'delegated',
        'owner' => 'classes/user.php and classes/UserProfileStore.php',
        'reason' => 'Student import validates rows and delegates each business write to the transaction-owning user and profile APIs.',
        'evidence' => 'ExcelHandler::importStudents calls User::create and User::ensureStudentProfile; this file contains no direct SQL mutation.',
    ],
    'admin/includes/official_document_page.php' => [
        'type' => 'false_positive',
        'owner' => 'admin/includes/official_document_page.php',
        'reason' => 'Read-only official-document presentation template; scanner write terms occur in deleted_at filtering and client-side live-update identifiers.',
        'evidence' => 'Server-side database statements are SELECT queries only; the form renders a document preview and performs no mutation.',
    ],
    'admin/specialist_requests.php' => [
        'type' => 'false_positive',
        'owner' => 'admin/specialist_requests.php',
        'reason' => 'Read-only specialist request list; the create call constructs a query service and does not create a business record.',
        'evidence' => 'StudentChangeRequestService::create is a factory and listForSpecialist executes the read path used by this page.',
    ],
    'admin/statements.php' => [
        'type' => 'false_positive',
        'owner' => 'admin/statements.php',
        'reason' => 'Read-only official-statement renderer; scanner write terms occur in deleted_at filtering and client-side live-update identifiers.',
        'evidence' => 'Server-side database statements are SELECT queries only; POST renders the selected document without persisting state.',
    ],
    'admin/ajax_bulk_student_accounts.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Accounts/StudentAccountBulkCommandService.php',
        'reason' => 'The endpoint validates admin session and CSRF, then delegates execution to StudentAccountBulkCommandService.',
        'evidence' => 'StudentAccountBulkCommandService::execute owns transaction and batch audit logging.',
    ],
    'admin/ajax_bulk_staff_accounts.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/StaffAccountBulkCommandService.php',
        'reason' => 'The endpoint validates admin session and CSRF, then delegates execution to StaffAccountBulkCommandService.',
        'evidence' => 'StaffAccountBulkCommandService::execute owns transaction and batch audit logging.',
    ],
    'admin/ajax_bulk_role_pages.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/StaffRolePageBulkCommandService.php',
        'reason' => 'The endpoint validates super_admin active session role and CSRF, then delegates execution to StaffRolePageBulkCommandService.',
        'evidence' => 'StaffRolePageBulkCommandService::execute owns transaction and audit logging.',
    ],

    // === Finance module classifications (003-finance-ledger-payroll) ===

    'admin/finance_vouchers.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/VoucherService.php',
        'reason' => 'The page validates admin session and CSRF, then delegates voucher creation to VoucherService which owns the transaction and GL journal creation.',
        'evidence' => 'VoucherService::postVoucher owns transaction, balance check, and journal entry creation.',
    ],
    'src/Modules/Finance/Application/BudgetService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/BudgetService.php',
        'reason' => 'Budget planning data (draft/reviewed/approved/locked); no financial movements posted; actuals are read-only from GL.',
        'evidence' => 'BudgetService creates budget/lines as planning data; actualForLine is a SELECT from posted GL.',
    ],
    'src/Modules/Finance/Application/DiscountService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/DiscountService.php',
        'reason' => 'Discount rules/awards/applications are configuration data; the service delegates audit to AuditService when wired by the caller.',
        'evidence' => 'createAward/applyDiscount create domain rows; no sub-ledger or GL posting in this service.',
    ],
    'src/Modules/Finance/Application/FeePlanService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/FeePlanService.php',
        'reason' => 'Fee plan/version management is configuration; activateVersion uses FOR UPDATE for safe activation.',
        'evidence' => 'createVersion/activateVersion manage plan versions; no financial movements posted here.',
    ],
    'src/Modules/Finance/Application/JournalEntryService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/JournalEntryService.php',
        'reason' => 'Creates GL journal entries linked 1:1 to sub-ledger transactions; delegates audit to AuditService when wired by the caller.',
        'evidence' => 'postJournalForPartyOperation creates journal entry + lines; isBalanced enforced before posting.',
    ],
    'src/Modules/Finance/Application/PayrollRunService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/SubledgerPostingService.php',
        'reason' => 'Delegates sub-ledger posting to SubledgerPostingService which owns the transaction boundary and audit.',
        'evidence' => 'postPayrollItem/postPayment call postingService->postPartyOperation inside the caller transaction.',
    ],
    'src/Modules/Finance/Application/ReceiptService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/SubledgerPostingService.php',
        'reason' => 'Delegates sub-ledger posting to SubledgerPostingService which owns the transaction boundary and audit.',
        'evidence' => 'postReceipt calls postingService->postPartyOperation inside the caller transaction.',
    ],
    'src/Modules/Finance/Application/StaffAdvanceService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/SubledgerPostingService.php',
        'reason' => 'Delegates sub-ledger posting to SubledgerPostingService; write-off enforces maker-checker.',
        'evidence' => 'issueAdvance/recordCashRepayment/writeOffAdvance call postingService->postPartyOperation.',
    ],
    'src/Modules/Finance/Application/StudentChargeService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/SubledgerPostingService.php',
        'reason' => 'Delegates sub-ledger posting to SubledgerPostingService which owns the transaction boundary and audit.',
        'evidence' => 'createCharge calls postingService->postPartyOperation inside the caller transaction.',
    ],
    'src/Modules/Finance/Application/VoucherService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/VoucherService.php',
        'reason' => 'Owns voucher creation transaction, balance check, and GL journal; delegates audit to AuditService when wired.',
        'evidence' => 'postVoucher owns transaction, verifies SUM(debit)=SUM(credit), enforces maker-checker.',
    ],
    'src/Modules/Finance/Contracts/Repositories/ReceiptRepository.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Finance/Contracts/Repositories/ReceiptRepository.php',
        'reason' => 'Interface only; no implementation or writes.',
        'evidence' => 'Abstract contract defining repository methods.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoChargeRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/StudentChargeService.php',
        'reason' => 'Repository executes SQL on behalf of StudentChargeService which owns the transaction and audit.',
        'evidence' => 'createCharge/addInstallment called inside StudentChargeService transaction.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoChargeInstallmentRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/PaymentAllocationService.php',
        'reason' => 'Installment state reads and locks are repository operations used by audited allocation workflows.',
        'evidence' => 'PaymentAllocationService owns the surrounding transaction and allocation audit event.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoStudentContractRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/StudentChargeService.php',
        'reason' => 'Student contract snapshots are created atomically with the plan charge and its mandatory audit event.',
        'evidence' => 'StudentChargeService::createChargeFromActivePlan owns transaction and finance_student_contract_create audit.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoStudentFinanceAccountRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/StudentChargeService.php',
        'reason' => 'Student finance account creation/linking is part of the audited atomic plan-charge workflow.',
        'evidence' => 'StudentChargeService::createChargeFromActivePlan owns transaction; posting audit covers the resulting financial operation.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoFeePlanRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/FeePlanService.php',
        'reason' => 'Repository executes SQL on behalf of FeePlanService which owns the transaction.',
        'evidence' => 'createVersion/addInstallment called inside FeePlanService.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoJournalEntryRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/JournalEntryService.php',
        'reason' => 'Repository executes SQL on behalf of JournalEntryService which owns the transaction and balance enforcement.',
        'evidence' => 'create/addLine/post called inside JournalEntryService transaction.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoAccountMappingHeaderRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/ControlAccountService.php',
        'reason' => 'Repository persists account-mapping headers on behalf of the application service that validates the mapping policy and owns orchestration.',
        'evidence' => 'ControlAccountService::createMapping delegates header persistence through AccountMappingHeaderRepository.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoAccountMappingLineRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/ControlAccountService.php and src/Modules/Finance/Application/JournalEntryService.php',
        'reason' => 'Repository persists mapping lines for ControlAccountService and supplies read-only operation mappings to JournalEntryService.',
        'evidence' => 'ControlAccountService::createMapping delegates validated line persistence; JournalEntryService consumes operation mappings through the contract.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoAdjustmentRepository.php' => [
        'type' => 'delegated', 'owner' => 'src/Modules/Finance/Application/UnappliedCreditService.php',
        'reason' => 'Repository persists debt adjustments inside the application-owned atomic posting and audit transaction.', 'evidence' => 'UnappliedCreditService::writeOffDebt.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoArchiveRepository.php' => [
        'type' => 'delegated', 'owner' => 'src/Modules/Finance/Application/ArchiveService.php',
        'reason' => 'Allow-listed archive state updates execute inside ArchiveService transaction and mandatory audit.', 'evidence' => 'ArchiveService::archive and restore.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoBudgetRepository.php' => [
        'type' => 'delegated', 'owner' => 'src/Modules/Finance/Application/BudgetService.php',
        'reason' => 'Budget planning writes execute inside BudgetService transaction and mandatory audit.', 'evidence' => 'BudgetService create/version/line/approve/lock methods.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoImportBatchRepository.php' => [
        'type' => 'delegated', 'owner' => 'src/Modules/Finance/Application/ImportService.php',
        'reason' => 'Import staging and posting writes execute inside ImportService transaction and mandatory audit.', 'evidence' => 'ImportService staging, count, posting, and abandonment methods.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoPaymentAllocationRepository.php' => [
        'type' => 'delegated', 'owner' => 'src/Modules/Finance/Application/ReceiptService.php and src/Modules/Finance/Application/UnappliedCreditService.php',
        'reason' => 'Allocation persistence and reversal are owned by audited receipt/refund application workflows.', 'evidence' => 'ReceiptService::postReceipt and UnappliedCreditService refund workflow.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoPayrollRunRepository.php' => [
        'type' => 'delegated', 'owner' => 'src/Modules/Finance/Application/PayrollRunService.php',
        'reason' => 'Payroll item/payment persistence executes inside atomic sub-ledger, GL, and audit orchestration.', 'evidence' => 'PayrollRunService::postPayrollItem and postPayment.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoRefundRepository.php' => [
        'type' => 'delegated', 'owner' => 'src/Modules/Finance/Application/UnappliedCreditService.php',
        'reason' => 'Refund rows execute inside maker-checker atomic posting and audit orchestration.', 'evidence' => 'UnappliedCreditService::postRefund.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoStaffAdvanceMovementRepository.php' => [
        'type' => 'delegated', 'owner' => 'src/Modules/Finance/Application/StaffAdvanceService.php',
        'reason' => 'Advance movements execute inside atomic staff sub-ledger, GL, and audit orchestration.', 'evidence' => 'StaffAdvanceService::postMovement.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoStaffAdvanceRepository.php' => [
        'type' => 'delegated', 'owner' => 'src/Modules/Finance/Application/StaffAdvanceService.php',
        'reason' => 'Advance headers and status changes execute inside atomic staff posting workflows.', 'evidence' => 'StaffAdvanceService::issueAdvance and postMovement.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoReceiptRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/ReceiptService.php',
        'reason' => 'Repository executes SQL on behalf of ReceiptService which owns the transaction.',
        'evidence' => 'allocateSequenceNumber/create/post called inside ReceiptService transaction.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoSubledgerAccountRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/SubledgerPostingService.php',
        'reason' => 'Repository executes SQL on behalf of SubledgerPostingService which owns the transaction and audit.',
        'evidence' => 'findOrCreate called inside postingService->postPartyOperation.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoSubledgerTransactionRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/SubledgerPostingService.php',
        'reason' => 'Repository executes SQL on behalf of SubledgerPostingService which owns the transaction and audit.',
        'evidence' => 'createTransaction/addLine/post called inside postingService->postPartyOperation.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoDiscountRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/DiscountService.php',
        'reason' => 'Repository executes SQL on behalf of DiscountService which owns the transaction.',
        'evidence' => 'createAward/applyDiscount called inside DiscountService.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoUnappliedCreditRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/ReceiptService.php',
        'reason' => 'Repository executes SQL on behalf of ReceiptService which owns the transaction and audit.',
        'evidence' => 'create/createApplication called inside ReceiptService transaction.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoVoucherRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/VoucherService.php',
        'reason' => 'Repository executes SQL on behalf of VoucherService which owns the transaction and balance check.',
        'evidence' => 'create/addLine called inside VoucherService::postVoucher.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoStaffCompensationRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/PayrollRunService.php',
        'reason' => 'Repository executes SQL on behalf of PayrollRunService which owns the transaction and audit.',
        'evidence' => 'createContract/addComponent called inside PayrollRunService transaction.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoCashboxRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/VoucherService.php',
        'reason' => 'Repository executes settlement SQL on behalf of VoucherService/caller which owns the transaction.',
        'evidence' => 'createSettlement/settleSettlement called inside caller transaction.',
    ],
    'src/Modules/Finance/Application/PaymentAllocationService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/SubledgerPostingService.php',
        'reason' => 'Delegates sub-ledger posting to SubledgerPostingService which owns the transaction boundary and audit.',
        'evidence' => 'autoAllocateToOldest/applyUnappliedCredit call postingService->postPartyOperation inside the caller transaction.',
    ],
    'src/Modules/Finance/Application/UnappliedCreditService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/SubledgerPostingService.php',
        'reason' => 'Delegates sub-ledger posting to SubledgerPostingService; refund/write-off enforce maker-checker.',
        'evidence' => 'refundUnappliedCredit/refundAllocation/writeOffDebt call postingService->postPartyOperation inside the caller transaction.',
    ],
    'src/Modules/Finance/Application/ImportService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/ImportService.php',
        'reason' => 'Staging writes no business data; posting requires maker-checker; correction is reversal batch.',
        'evidence' => 'createBatch/addRow are staging; postBatch enforces maker-checker and refuses batches with errors.',
    ],
    'src/Modules/Finance/Application/ExportService.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Finance/Application/ExportService.php',
        'reason' => 'Export is read-only; logExport inserts a batch log row (abandoned status) as audit metadata, not a business write.',
        'evidence' => 'logExport inserts metadata; tempFilePath is a path generator.',
    ],
    'src/Modules/Finance/Application/ArchiveService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/ArchiveService.php',
        'reason' => 'Archive/restore are status changes on configuration tables; posted movements are never hard-deleted.',
        'evidence' => 'archive/restore UPDATE status only; no financial movement writes.',
    ],
    'src/Modules/Finance/Application/DailySettlementService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/DailySettlementService.php',
        'reason' => 'Settlement is an operational record; expectedTotal is read-only from receipts.',
        'evidence' => 'openSettlement/settleSettlement create/update settlement records; expectedTotal is SELECT.',
    ],
    'src/Modules/Finance/Application/ReportService.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Finance/Application/ReportService.php',
        'reason' => 'All methods are SELECT queries; no writes.',
        'evidence' => 'trialBalance/collectionSummary/debtAging/payrollSummary/budgetVsActual are read-only.',
    ],
    'src/Modules/Finance/Application/SubledgerPostingService.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/SubledgerPostingService.php',
        'reason' => 'Owns the transaction boundary and audit orchestration for all party operations.',
        'evidence' => 'postPartyOperation/postReversal call txRepo inside the caller transaction.',
    ],
    'src/Modules/Finance/Contracts/Repositories/ChargeInstallmentRepository.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Finance/Contracts/Repositories/ChargeInstallmentRepository.php',
        'reason' => 'Interface only; the SQL keyword appears in PHPDoc, not in executable code.',
        'evidence' => 'Abstract contract defining repository methods.',
    ],
    'src/Modules/Finance/Contracts/Repositories/ReceiptNumberSequenceRepository.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Finance/Contracts/Repositories/ReceiptNumberSequenceRepository.php',
        'reason' => 'Interface only; the SQL keyword appears in PHPDoc, not in executable code.',
        'evidence' => 'Abstract contract defining repository methods.',
    ],
    'admin/finance_import_export.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/ImportService.php and src/Modules/Finance/Application/FinanceApprovalWorkflowService.php',
        'reason' => 'The authenticated CSRF-protected page stages imports and submits post/reversal requests through Finance application services.',
        'evidence' => 'No direct SQL; ImportService owns staging audit and FinanceApprovalWorkflowService owns maker-checker posting.',
    ],
    'classes/FinancePeriodGuard.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Finance/Application/FinancePeriodService.php',
        'reason' => 'The compatibility guard is read-only and only selects the year/period state to reject writes.',
        'evidence' => 'All close/reopen SQL was removed; audited lifecycle writes are owned by FinancePeriodService.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoFinanceApprovalRequestRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/FinanceApprovalWorkflowService.php',
        'reason' => 'Approval request persistence executes only on behalf of the application-owned maker-checker workflow.',
        'evidence' => 'FinanceApprovalWorkflowService creates, locks, decides, and audits requests in one transaction.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoFinancePeriodRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/FinancePeriodService.php',
        'reason' => 'Finance-period persistence executes only inside the audited application lifecycle.',
        'evidence' => 'FinancePeriodService owns creation, close/reopen validation, maker-checker enforcement, transaction, and audit.',
    ],
    'classes/FinanceLegacyAdapter.php' => [
        'type' => 'delegated',
        'owner' => 'Finance and Transport compatibility application services',
        'reason' => 'The authenticated adapter translates legacy requests and delegates every supported mutation to an application service; it executes no SQL.',
        'evidence' => 'Fee definitions, collections, staff contracts, and bus assignments are dispatched to their transaction-owning audited services after CSRF validation.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoBusFeeScheduleRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/BusFeeScheduleService.php',
        'reason' => 'Bus-fee schedule persistence is invoked only inside the application-owned transaction and mandatory audit event.',
        'evidence' => 'BusFeeScheduleService::activate and archive own the transaction and record the corresponding shared audit event.',
    ],
    'src/Modules/Finance/Infrastructure/Pdo/PdoLegacyCompatibilityRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Finance/Application/LegacyFeeDefinitionService.php and src/Modules/Finance/Application/LegacyStaffFinanceCompatibilityService.php',
        'reason' => 'Compatibility mappings are provenance metadata written inside the translated business operation transaction.',
        'evidence' => 'Legacy fee and staff compatibility services persist the mapping only with the new owned record and its mandatory audit workflow.',
    ],
    'src/Modules/Transport/Infrastructure/PdoStudentBusAssignmentRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Transport/Application/LegacyStudentBusAssignmentService.php',
        'reason' => 'Transport assignment writes execute only inside the source-owned transaction and shared audit workflow.',
        'evidence' => 'LegacyStudentBusAssignmentService validates the complete batch, archives unassignment, and records create/update/archive events atomically.',
    ],
    'src/Modules/Staff/StaffBiometricIdentityService.php' => [
        'type' => 'delegated',
        'owner' => 'admin/biometric_devices.php and admin/ajax/biometric_device_actions.php',
        'reason' => 'The biometric identity helper mutates only inside a caller-owned transaction and deliberately returns locked before/after snapshots for the mandatory shared audit record.',
        'evidence' => 'Both synchronizeWithinTransaction callers begin one PDO transaction, record the staff_profiles change through AuditService, and commit only after the audit write succeeds; every catch path rolls the transaction back.',
    ],
    'admin/hr_policy_calendar.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Attendance/Application/SchedulePolicyCommandService.php',
        'reason' => 'The authenticated CSRF-protected controller normalizes input and delegates every policy/calendar mutation to the transaction-owning audited application command service.',
        'evidence' => 'save_schedule_policy_draft, publish_schedule_policy, and save_calendar_exception call only AttendanceModuleFactory application services; the page contains no business SQL.',
    ],
    'src/Modules/Attendance/Infrastructure/PdoLegacyStaffShiftRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Attendance/Application/LegacyStaffShiftCompatibilityService.php',
        'reason' => 'Legacy shift persistence executes only inside the compatibility application service transaction and its mandatory undoable audit adapter.',
        'evidence' => 'saveDefaultShift, saveOverride, and deleteOverride call the repository within AttendanceTransactionManager and persist AuditService events before commit; audit failure is covered by rollback tests.',
    ],
    'src/Modules/Attendance/Infrastructure/PdoSchedulePolicyRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Attendance/Application/SchedulePolicyCommandService.php and src/Modules/Attendance/Application/ScheduleChangeRequestService.php',
        'reason' => 'Schedule persistence is a contract adapter invoked only by transaction-owning command services that require the shared AuditEventWriter; participant-lock rows are concurrency coordination metadata in the same transaction.',
        'evidence' => 'staff_hr_schedule_policy_command_test.php and staff_hr_schedule_change_contract_test.php prove business writes, receipts, participant serialization, and mandatory audit share one transaction and roll back when audit persistence fails.',
    ],
    'src/Modules/Attendance/Infrastructure/PdoBiometricIdentityMappingRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Attendance/Application/BiometricIdentityMappingService.php',
        'reason' => 'The adapter writes only Attendance-owned effective-dated identity rows and is invoked by the transaction-owning mapping service through a narrow repository contract.',
        'evidence' => 'staff_hr_biometric_ingestor_test.php proves overlap rejection, natural-key replay, historical identity reuse, and complete rollback when the mandatory shared audit write fails.',
    ],
    'src/Modules/Attendance/Infrastructure/PdoAttendanceEventRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Attendance/Application/AttendanceEventIngestor.php',
        'reason' => 'Batch and append-only raw-event persistence is reachable only through the transaction-owning ingestor and its shared AuditEventWriter dependency.',
        'evidence' => 'staff_hr_biometric_ingestor_test.php proves batch/event idempotency, immutable historical snapshots, sensitive-payload exclusion, and atomic rollback of batch plus child events on audit failure.',
    ],
    'src/Modules/Attendance/Infrastructure/PdoAlternativeAttendanceEventRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Attendance/Application/AlternativeAttendanceRecorder.php',
        'reason' => 'Alternative-event persistence is reachable through the transaction-owning recorder, which requires independent authorization and a shared AuditEventWriter before its transaction can commit.',
        'evidence' => 'staff_hr_alternative_attendance_recorder_test.php and guarded staff_hr_alternative_attendance_integration_test.php prove idempotency, self-review prevention, raw immutability, final-review freezing, and rollback when mandatory audit persistence fails.',
    ],
    'src/Modules/Attendance/Infrastructure/PdoAttendanceAdjustmentRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Attendance/Application/AttendanceAdjustmentService.php',
        'reason' => 'Correction, recalculation-run, version, and child-row persistence runs only inside the transaction-owning adjustment workflow, which requires independent authorization and the shared AuditEventWriter before committing.',
        'evidence' => 'guarded staff_hr_attendance_adjustment_integration_test.php proves idempotent drafts, requester/decider separation, source-version staleness, immutable raw evidence, successor lineage, finality, and full rollback when the mandatory audit write fails.',
    ],
    'src/Modules/Attendance/Infrastructure/PdoAttendanceShadowRunRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Attendance/Application/AttendanceShadowRunService.php and src/Modules/Attendance/Application/AttendanceRecalculationService.php',
        'reason' => 'Shadow comparison and immutable official-successor persistence are reachable only through transaction-owning Attendance services that complete a mandatory shared AuditEventWriter event before committing.',
        'evidence' => 'staff_hr_attendance_shadow_run_test.php, guarded staff_hr_attendance_shadow_run_integration_test.php, and staff_hr_attendance_recalculation_test.php prove idempotency, redacted event projection, version lineage, classified legacy differences, and rollback when mandatory audit persistence fails.',
    ],
    'src/Modules/Attendance/Infrastructure/PdoAttendancePeriodRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Attendance/Application/AttendancePeriodService.php',
        'reason' => 'Period and late-change persistence is reachable only through the transaction-owning period service, which records every close, reopen decision, change fact, and applied recalculation before commit.',
        'evidence' => 'staff_hr_attendance_recalculation_integration_test.php proves locked-period rejection, late approval/reversal routing, decision replay, atomic batch rollback, and audit rollback in a state-isolated transaction harness.',
    ],
    'src/Modules/Attendance/Infrastructure/PdoAttendanceReportProjectionRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Attendance/Application/AttendanceReportProjector.php',
        'reason' => 'Versioned report-run and aggregate persistence is reachable only through the transaction-owning projector, which uses a stable official-day snapshot, retires a current aggregate only to append a linked successor, and records one mandatory shared audit event before commit.',
        'evidence' => 'staff_hr_attendance_report_projector_test.php proves bounded cursor reads, idempotent replay, changed-source successor lineage, monthly/annual/range guards, dimension fail-closed behavior, and full rollback when audit persistence fails.',
    ],
    'src/Modules/Attendance/Infrastructure/AttendanceModuleFactory.php' => [
        'type' => 'delegated',
        'owner' => 'Attendance transaction-owning application command services, including schedule, legacy-shift, biometric mapping, raw-event ingestion, correction, shadow comparison, period control, and the Staff coverage gateway',
        'reason' => 'The infrastructure composition root performs no persistence; it wires repository adapters only into transaction-owning application services with mandatory shared audit dependencies and exposes the narrow Staff coverage contract without exposing tables.',
        'evidence' => 'Factory, ingestion, correction, shadow-run, period integration, and approved-coverage publisher tests prove that each write path receives PdoAttendanceTransactionManager plus the shared AuditService/AuditEventWriter; impact/admin query paths remain read-only.',
    ],
    'src/Modules/Staff/Infrastructure/PdoPermissionRequestRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Permission/PermissionRequestService.php',
        'reason' => 'The PDO adapter only persists request state and monthly slices inside the transaction owned by PermissionRequestService; the service requires the shared AuditEventWriter before committing every lifecycle transition.',
        'evidence' => 'staff_hr_permission_request_test.php proves draft/create/update/submit/withdraw/cancel behavior, idempotency, overlap locking, quota integration, and rollback when the mandatory audit event writer fails.',
    ],
    'src/Modules/Staff/Infrastructure/PdoPermissionQuotaLedgerRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Permission/PermissionQuotaLedger.php',
        'reason' => 'The PDO adapter only serializes the account/idempotency locks and persists the immutable movement inside the transaction owned by PermissionQuotaLedger; the service requires the shared AuditEventWriter before committing.',
        'evidence' => 'staff_hr_permission_quota_ledger_test.php and guarded staff_hr_permission_quota_concurrency_test.php prove idempotency, limit enforcement, concurrent reserve/consume/release, immutable movement history, and rollback when mandatory audit persistence fails.',
    ],
    'src/Modules/Staff/Contracts/LeaveBalanceLedgerGateway.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Staff/Contracts/LeaveBalanceLedgerGateway.php',
        'reason' => 'Interface-only application boundary; lexical record/carry/reverse method names do not mutate data.',
        'evidence' => 'The file declares no PDO dependency, SQL, implementation, or business write.',
    ],
    'src/Modules/Staff/Contracts/LeaveBalanceLedgerRepository.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Staff/Contracts/LeaveBalanceLedgerRepository.php',
        'reason' => 'Interface-only persistence contract; transactional and update method signatures do not execute writes.',
        'evidence' => 'Concrete SQL exists only in PdoLeaveBalanceLedgerRepository and is owned by LeaveBalanceLedger.',
    ],
    'src/Modules/Staff/Contracts/LeaveRequestRepository.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Staff/Contracts/LeaveRequestRepository.php',
        'reason' => 'Interface-only persistence contract; lifecycle method signatures do not execute writes.',
        'evidence' => 'Concrete SQL exists only in PdoLeaveRequestRepository and is owned by LeaveRequestService.',
    ],
    'src/Modules/Staff/Infrastructure/PdoLeaveBalanceLedgerRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Leave/LeaveBalanceLedger.php',
        'reason' => 'The PDO adapter only locks account/idempotency rows and persists account caches plus append-only movements inside the ledger-owned transaction; the application service requires AuditEventWriter before commit.',
        'evidence' => 'staff_hr_leave_balance_test.php proves grant/accrue/reserve/consume/release, cross-year carry, expiry/reversal, stale-lock rejection, replay, and rollback when the mandatory audit event fails.',
    ],
    'src/Modules/Staff/Infrastructure/PdoLeaveFinanceEffectRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Leave/LeaveFinanceEffectService.php',
        'reason' => 'The PDO adapter persists only Staff-owned staff_external_effects and locks approved leave snapshots/day allocations; LeaveFinanceEffectService validates the immutable policy fact, queues or transitions the outbox, and requires shared audit evidence before each transaction commits.',
        'evidence' => 'staff_hr_leave_finance_effect_test.php proves month-split paid/unpaid facts, signed reversal facts, stable idempotency, Finance-contract-only dispatch, retry behavior, and rollback when audit persistence fails.',
    ],
    'src/Modules/Staff/Infrastructure/PdoLeaveRequestRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Leave/LeaveRequestService.php',
        'reason' => 'The PDO adapter only locks Staff-owned request/allocation rows and persists commands validated by LeaveRequestService, which re-resolves policy and workflow evidence, invokes the audited immutable balance ledger, and records mandatory audit events before the transaction can commit.',
        'evidence' => 'staff_hr_leave_request_test.php proves draft/update/submit lifecycle, self ownership, idempotency, overlap enforcement, successor records, balance reservation, policy/workflow snapshotting, and rollback when audit persistence fails.',
    ],
    'src/Modules/Staff/Infrastructure/PdoLeaveStaffingOverrideRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Leave/LeaveStaffingOverrideService.php',
        'reason' => 'The PDO adapter stores only the append-only staffing-exception evidence and exposes a locked matching-decision query; LeaveStaffingOverrideService validates the live policy requirement, role authority, reason, idempotency, request projection, and mandatory shared audit inside the request transaction.',
        'evidence' => 'staff_hr_leave_staffing_override_test.php proves authorized approve/reject, required reason, idempotent replay, stale-request invalidation, and absence of a balance reservation before normal leave submission.',
    ],
    'src/Modules/Staff/Infrastructure/PdoLeaveStaffingReadRepository.php' => [
        'type' => 'false_positive',
        'owner' => 'src/Modules/Staff/Infrastructure/PdoLeaveStaffingReadRepository.php',
        'reason' => 'The adapter executes read-only blackout and availability queries; SELECT FOR UPDATE is used solely to serialize capacity evaluation before LeaveRequestService performs its separately audited write.',
        'evidence' => 'The adapter contains no INSERT, UPDATE, DELETE, DDL, or transaction commit; staff_hr_leave_request_test.php proves blocked staffing/blackout submissions leave the balance ledger untouched.',
    ],
    'src/Modules/Staff/Infrastructure/PdoLeaveAttachmentRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Leave/LeaveAttachmentService.php',
        'reason' => 'The PDO adapter locks and replaces Staff-owned draft attachment metadata only inside the attachment service transaction; it contains no authorization, file handling, or independent business transition.',
        'evidence' => 'staff_hr_leave_attachment_integration_test.php proves authorization before storage, guarded MIME/name/size validation, replacement lineage, and rollback of both metadata and the new private file when persistence or the mandatory audit event fails.',
    ],
    'src/Modules/Staff/Infrastructure/PdoDisciplineCaseRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Discipline/DisciplineCaseService.php',
        'reason' => 'The PDO adapter only locks Staff-owned incident, case, and party records and persists commands inside the application-owned transaction. DisciplineCaseService validates current authorization, source/subject immutability, idempotency, and version state, then requires one shared AuditEventWriter event before commit.',
        'evidence' => 'staff_hr_discipline_case_service_test.php proves incident/case idempotency, immutable subject/source linkage, party conflict/withdrawal, reasoned cancellation, authorization rejection before persistence, and full transaction rollback when mandatory audit persistence fails.',
    ],
    'src/Modules/Staff/Infrastructure/PdoErtaqTicketRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Ertaq/ErtaqTicketService.php',
        'reason' => 'The PDO adapter locks only Staff-owned Ertaq ticket and assignment rows plus the user existence row inside the application transaction. ErtaqTicketService derives policy/SLA evidence through a contract, checks live authorization and assignment scope, uses idempotency and optimistic locks, preserves predecessor assignments, and requires shared AuditEventWriter evidence before commit.',
        'evidence' => 'staff_hr_ertaq_ticket_service_test.php proves self-scoped creation, policy-derived confidential classification, idempotent ticket/assignment retries, assignment succession, constrained lifecycle transitions, authorization-before-persistence, confidential receipt/audit metadata, and rollback when mandatory audit persistence fails.',
    ],
    'src/Modules/Staff/Infrastructure/PdoErtaqConversationRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Ertaq/ErtaqConversationService.php',
        'reason' => 'The PDO adapter locks and writes only Staff-owned Ertaq message, party, link, withdrawal, and ticket-state rows inside the application transaction. ErtaqConversationService checks live authorization, derives visibility from that boundary, enforces message/party/link idempotency, retains scalar cross-module links without a direct join, and records append-only withdrawal evidence before the shared audit event commits.',
        'evidence' => 'staff_hr_ertaq_conversation_service_test.php proves server-derived visibility, immutable message retry behavior, parties and collective/discipline scalar links, requester-only withdrawal request, independent withdrawal decision, exact prior-state restoration, no hard-delete behavior, authorization rejection, and mandatory-audit rollback.',
    ],
    'src/Modules/Staff/Infrastructure/PdoErtaqUrgentRoutingRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Ertaq/ErtaqUrgentRoutingService.php',
        'reason' => 'The PDO adapter locks Staff-owned Ertaq ticket, urgent-route, and minimal party-identifier rows only. ErtaqUrgentRoutingService derives a protection team/recipient route through a live authorization contract, rejects any conflicted recipient, stores the exclusion snapshot as private evidence, and records route/acknowledgement audit evidence before commit without notification, Finance, discipline, or access writes.',
        'evidence' => 'staff_hr_ertaq_urgent_routing_service_test.php proves conflict exclusion, route idempotency, protection acknowledgement, no external side effect dependency, authorization-before-persistence, and rollback of both urgent event and ticket state when mandatory audit fails.',
    ],
    'src/Modules/Staff/Infrastructure/PdoErtaqSlaRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Ertaq/ErtaqSlaService.php',
        'reason' => 'The PDO adapter locks and writes only Staff-owned Ertaq ticket deadline and SLA-event rows. ErtaqSlaService derives deterministic queue records from the frozen policy window, performs optimistic deadline renewal only during an already-authorized reopen transition, checks live worker/escalation authorization, cancels inactive or superseded records before routing, and requires shared audit evidence in the same transaction.',
        'evidence' => 'staff_hr_ertaq_sla_service_test.php proves deterministic scheduling, retry idempotency, live escalation authorization, superseded-window and terminal cancellation, reopened deadline renewal, target failure rollback, mandatory-audit rollback, and absence of push, content, or disciplinary side effects.',
    ],
    'src/Modules/Staff/Infrastructure/PdoErtaqAttachmentNotificationRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Ertaq/ErtaqAttachmentNotificationService.php',
        'reason' => 'The PDO adapter locks only Staff-owned Ertaq ticket/message rows and private attachment metadata. ErtaqAttachmentNotificationService authorizes before invoking storage, verifies ticket/message scope and normalized private metadata, records the shared audit event before the notification enqueue, cleans the newly moved file on any transaction failure, and never returns storage paths or filenames.',
        'evidence' => 'staff_hr_ertaq_attachment_notification_service_test.php proves authorization-before-storage, message/ticket binding, idempotent retry, neutral recipient-controlled notification metadata, audit-before-notification rollback, notification rejection cleanup, and a no-recipient path without an invented route.',
    ],
    'src/Modules/Staff/Infrastructure/PdoDisciplineInvestigationRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Discipline/DisciplineInvestigationService.php',
        'reason' => 'The PDO adapter only locks and persists Staff-owned investigation/evidence records inside the application-owned transaction. DisciplineInvestigationService validates current authorization, recorder/investigator separation, custody predecessors, source-reference boundaries, private storage metadata, idempotency, and requires shared audit evidence before commit.',
        'evidence' => 'staff_hr_discipline_investigation_service_test.php proves independent assignment, immutable linked-source references, custody chaining, private MIME/name/size/upload-error rejection, collision-resistant storage, authorization before storage, and rollback of both metadata and a newly moved file when persistence or mandatory audit fails.',
    ],
    'src/Modules/Staff/Infrastructure/PdoDisciplineDecisionRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Discipline/DisciplineDecisionService.php and src/Modules/Staff/Application/Discipline/DisciplineDecisionApprovalOutcomeHandler.php',
        'reason' => 'The PDO adapter only locks and compare-and-swap transitions Staff-owned decision/case records. The proposal service freezes the shared approval snapshot and requires audit evidence; the approval outcome handler alone issues or cancels a proposed decision, records neutral notification status, and never writes Finance directly.',
        'evidence' => 'staff_hr_discipline_decision_service_test.php proves workflow-linked proposal idempotency, recorder/investigator/preparer/finalizer separation, approved/rejected outcome handling, neutral notification metadata, delivery-failure durability, subject-only receipt, and rollback when the mandatory audit event fails.',
    ],
    'src/Modules/Staff/Infrastructure/PdoDisciplineAppealRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Discipline/DisciplineAppealService.php',
        'reason' => 'The PDO adapter only locks and compare-and-swap transitions Staff-owned appeal, temporary-measure, reopen-event, and case records inside the application transaction. DisciplineAppealService freezes the decision policy window, verifies separated actors, uses append-only reopen resolutions, records all final outcomes through AuditEventWriter, and has no external Access or Finance writer.',
        'evidence' => 'staff_hr_discipline_appeal_service_test.php proves subject-only appeal, frozen appeal-window/SLA/suspension policy, reviewer conflict exclusion, withdrawal/expiry return, separated temporary-measure authorization/review, linked reopen request/authorization, idempotency, and audit rollback.',
    ],
    'src/Modules/Staff/Infrastructure/PdoDisciplineFinanceEffectRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Discipline/DisciplineFinanceEffectService.php',
        'reason' => 'The PDO adapter persists and leases only Staff-owned discipline Finance fact intents. DisciplineFinanceEffectService validates the issued frozen policy snapshot, creates deterministic apply/reversal facts, prevents removal of an uncertain claim, and records every queue, cancellation, acceptance, retry, and final period rejection through the shared audit writer.',
        'evidence' => 'staff_hr_discipline_finance_integration_test.php proves immutable duplicate replay, closed-period final rejection without resubmission, signed reversal facts, cancellation before dispatch, and the absence of direct Finance-table writes.',
    ],
    'src/Modules/Staff/Infrastructure/PdoLegacyPermissionRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Permission/LegacyPermissionCompatibilityService.php',
        'reason' => 'The compatibility PDO adapter persists only the stable staff_permissions route inside the application-owned callback transaction; the service invokes the mandatory undo-aware shared audit writer before that transaction can commit.',
        'evidence' => 'staff_hr_legacy_permission_compatibility_service_test.php and guarded staff_hr_legacy_permission_compatibility_integration_test.php prove validation-before-write, audit ordering, audit-failure rollback, and stable legacy field/action compatibility.',
    ],
    'src/Modules/Staff/Infrastructure/PdoPermissionRequestRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Permission/PermissionRequestService.php',
        'reason' => 'The PDO adapter owns no business transition: it locks the staff/request/period rows and persists only commands validated by PermissionRequestService, which resolves the dated policy and workflow snapshot, calls the audited quota ledger, and requires a shared AuditEventWriter before commit.',
        'evidence' => 'staff_hr_permission_request_test.php and guarded staff_hr_permission_request_integration_test.php prove self ownership, idempotent draft/submit lifecycle, monthly slicing, overlap/notice/retroactive checks, quota reserve/release, one-way exception evidence, and full rollback when audit persistence fails.',
    ],
    'src/Modules/Staff/Infrastructure/Approval/PdoApprovalWorkflowRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Approval/ApprovalWorkflowService.php',
        'reason' => 'The PDO adapter only locks and persists immutable workflow-instance evidence under the transaction owned by ApprovalWorkflowService; the service records mandatory shared audit evidence before the outer transaction commits and invokes the resource outcome handler in that same transaction.',
        'evidence' => 'staff_hr_approval_concurrency_test.php proves optimistic locking, idempotent submissions and decisions, quorum, tie, rejection, same-actor merge, reassignment, escalation, and full rollback when audit persistence fails.',
    ],
    'src/Modules/Staff/Infrastructure/Approval/PdoApprovalWorkflowAdministrationRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Approval/ApprovalWorkflowAdministrationService.php',
        'reason' => 'The PDO adapter only locks and persists workflow/delegation administration rows inside the application-owned transaction; the service validates immutable version publication, scope conflict, and account eligibility and requires the shared AuditEventWriter before commit.',
        'evidence' => 'staff_hr_approval_administration_service_test.php proves draft/publish, previous-version closure, overlap rollback, delegation conflict/terminal/activation rules, redacted audit detail, and complete rollback on mandatory audit failure.',
    ],
    'src/Modules/Staff/Infrastructure/Organization/PdoStaffOrganizationRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Organization/StaffOrganizationService.php',
        'reason' => 'The PDO adapter locks and persists only Staff-owned effective-dated organization commands inside the application service transaction; the service rejects overlap and manager-cycle ambiguity and requires the shared AuditEventWriter before the transaction commits.',
        'evidence' => 'staff_hr_organization_service_test.php proves actor authorization, effective-date conflict rejection, manager cycle prevention, concurrent secondary assignment, and rollback when the mandatory audit writer fails.',
    ],
    'src/Modules/Staff/Infrastructure/Organization/PdoStaffOrganizationCorrectionRepository.php' => [
        'type' => 'delegated',
        'owner' => 'src/Modules/Staff/Application/Organization/StaffOrganizationCorrectionService.php',
        'reason' => 'The PDO adapter persists only immutable Staff-owned correction previews, independent decisions, and exact impact intents inside the application-owned transaction. StaffOrganizationCorrectionService validates the frozen scope, forbids requester self-approval, requires a live super-admin or effective HR-manager approver, publishes only the frozen impact, models reversal as a later row, and requires shared audit evidence before commit.',
        'evidence' => 'staff_hr_organization_correction_test.php proves idempotent frozen previews, independent authorization, exact scoped publication, append-only reversal, redacted audit details, and full rollback when impact publication or mandatory audit fails; staff_hr_organization_correction_integration_test.php proves the MariaDB migration and update/delete guards on a disposable *_test database.',
    ],
    'admin/export_student_numbers_report.php' => [
        'type' => 'false_positive',
        'owner' => 'admin/export_student_numbers_report.php',
        'reason' => 'Authenticated read-only export renderer; the detected service calls write an in-memory spreadsheet to the HTTP response and do not mutate business or file metadata.',
        'evidence' => 'The endpoint parses client-supplied report rows, builds a PhpSpreadsheet workbook, saves only to php://output, and contains no database connection, SQL mutation, or persistent file write.',
    ],
];
